services:
  jupyterlab:
    image: jupyter/base-notebook:frozen-20260324
    container_name: jupyterlab
    user: root
    environment:
      - NB_UID=1001
      - NB_GID=1001
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - JUPYTER_TOKEN=${JUPYTERLAB_TOKEN:-admin}
    networks:
      - digitaltwins
    ports:
      - "${JUPYTERLAB_BIND_ADDRESS:-0.0.0.0}:8008:8888"
    volumes:
      - ./notebook_workspace:/home/jovyan/work
    command: >
      start-notebook.sh 
      --NotebookApp.base_url='/jupyter' 
      --NotebookApp.allow_origin='https://test.digitaltwins.auckland.ac.nz'
      --NotebookApp.trust_xheaders=True
    restart: unless-stopped

#volumes:
#  notebook_workspace:
#    driver: local
#
#networks:
#  digitaltwins:
#    driver: bridge
