services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --http-relative-path /auth
    environment:
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - digitaltwins

  jupyterlab:
    image: jupyter/base-notebook:frozen-20260324
    container_name: jupyterlab # <--- AND THIS ONE
    environment:
      - JUPYTER_TOKEN="admin"
      - JUPYTER_SERVER_APP_BASE_URL=/jupyter
    command: start-notebook.sh --ServerApp.base_url=/jupyter --ServerApp.token=''
    networks:
      - digitaltwins
    
networks:
  digitaltwins:
    external: true  # This tells the child "look for this in the parent"
