services:
  portal-backend:
    extends:
      file: ./services/portal/DigitalTWINS-Portal/docker-compose.yml
      service: portal-backend
    restart: unless-stopped
    networks:
      - digitaltwins
  portal-frontend:
    extends:
      file: ./services/portal/DigitalTWINS-Portal/docker-compose.yml
      service: portal-frontend
    restart: unless-stopped
    networks:
      - digitaltwins
#  hapi-fhir:
#    extends:
#      file: ./services/hapi-fhir/docker-compose.yml
#      service: hapi-fhir
#    restart: unless-stopped
#    networks:
#      - digitaltwins
#  hapi-fhir-postgres:
#    extends:
#      file: ./services/hapi-fhir/docker-compose.yml
#      service: hapi-fhir-postgres
#    restart: unless-stopped
#    networks:
#      - digitaltwins

include:
  # to run only a specific included project with the root .env: sudo docker compose -f services/<service_name>/docker-compose.yml --env-file ./.env up

  # Keycloak
  - path:
    - services/keycloak/docker-compose.yml
    project_directory: services/keycloak
  # postgres
  - path:
    - services/postgres/docker-compose.yml
    project_directory: services/postgres
  # Airflow
  - path:
    - services/airflow/docker-compose.yml
    - services/airflow/network-override.yml
    project_directory: services/airflow
  # SEEK
  - path:
    - services/seek/ldh-deployment/docker-compose.yml
    - services/seek/network-override.yml
    project_directory: services/seek/ldh-deployment
  # MinIO
  - path:
    - services/minio/docker-compose.yml
    project_directory: services/minio
  # PACS
  - path:
    # PACS (Orthanc)
    - services/pacs/docker-compose.yml
    project_directory: services/pacs
  # digitaltwins-api
  - path:
    - services/api/digitaltwins-api/docker-compose.yml
    project_directory: services/api/digitaltwins-api
  # JupyterLab
  - path:
    - services/jupyterlab/docker-compose.yml
    project_directory: services/jupyterlab

volumes:
  portal_datasets:
    driver: local
  plugin_database:
    driver: local
  hapi_fhir_postgres:
    driver: local
  nginx_plugin_configs:
    driver: local

networks:
  digitaltwins:
    driver: bridge
    name: digitaltwins

# create networks if not exists
# sudo docker network create digitaltwins
