#!/bin/bash

############ parameters ########################
CLOUD_USER=ubuntu
ACME_SERVER=https://acme.zerossl.com/v2/DV90
# Apparently these next 2 are only needed on the initial cert issue
EAB_KID=$(<~/keys/eab_kid.key) || exit 1
EAB_HMAC_KEY=$(<~/keys/eab_hmac_key.key) || exit 1

export TZ=Pacific/Auckland
now=$(date '+%Y%m%d%H%M%S')
LOG_FILE=$HOME/logs/cert_renew.$now
CERTBOT_DIR=$HOME/certs
CERTS_DIR=$HOME/certs
EMAIL=matt.pestle@auckland.ac.nz
DOMAIN=test.digitaltwins.auckland.ac.nz
#WEB_STOP_COMMAND="sudo systemctl stop nginx"
#WEB_START_COMMAND="sudo systemctl start nginx"
CHAIN_FILE_NM=fullchain.pem
KEY_FILE_NM=privkey.pem
CHAIN=$CERTBOT_DIR/config/live/${DOMAIN}/$CHAIN_FILE_NM
KEY=$CERTBOT_DIR/config/live/${DOMAIN}/$KEY_FILE_NM
# Suggest making WITHIN_DAYS=29 and putting this on cron every week
WITHIN_DAYS=29
# Maybe something like this ...
## Check cert every week, renewing if it's going to expire within a window
## (the window set in the script should be larger than 7 days)
## This is 19:46 Sunday night, but remember this is system time -
## probably UTC so this is in the NZ morning on Tue.
#46 19 * * Sun $HOME/certs/renew_cert
####################################################

echo
date
echo

which openssl > /dev/null || {
    echo openssl not installed
    exit 1
}

((WITHIN_SEC=WITHIN_DAYS*24*60*60))
sudo openssl x509 -checkend $WITHIN_SEC -in $CHAIN && {
    echo "Certificate is fine for the next $WITHIN_DAYS days. Nothing to do."
    exit 0
}

cd $CERTBOT_DIR || exit 1

sudo certbot certonly -n \
	--config-dir ./config \
	--work-dir ./work \
	--logs-dir ./logs \
	--standalone \
	--server $ACME_SERVER \
	--agree-tos \
        --eab-kid "$EAB_KID" \
        --eab-hmac-key "$EAB_HMAC_KEY" \
	-m $EMAIL \
	--cert-name $DOMAIN \
	-d $DOMAIN || {
	echo Error renewing cert with certbot
	exit 1
}

sudo cp $CHAIN $CERTS_DIR/$CHAIN_FILE_NM || exit 1
sudo cp $KEY $CERTS_DIR/$KEY_FILE_NM || exit 1
sudo chown ${CLOUD_USER}:${CLOUD_USER} $CERTS_DIR/$CHAIN_FILE_NM || exit 1
sudo chown ${CLOUD_USER}:${CLOUD_USER} $CERTS_DIR/$KEY_FILE_NM || exit 1
sudo chmod 444 $CERTS_DIR/$CHAIN_FILE_NM || exit 1
sudo chmod 400 $CERTS_DIR/$KEY_FILE_NM || exit 1

# To revoke:
# sudo certbot revoke       --config-dir ./config  --cert-name $DOMAIN
# To inspect:
# sudo certbot certificates --config-dir ./config
