#!/bin/bash

: ${AIRFLOW_KEYCLOAK_CLIENT_ID:?}
: ${AIRFLOW_KEYCLOAK_CLIENT_SECRET:?}
U=mp1
P=mp1

curl -s -X POST \
  "https://test.digitaltwins.auckland.ac.nz/auth/realms/digitaltwins/protocol/openid-connect/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=password" \
  -d "client_id=${AIRFLOW_KEYCLOAK_CLIENT_ID}" \
  -d "client_secret=${AIRFLOW_KEYCLOAK_CLIENT_SECRET}" \
  -d "username=$U" \
  -d "password=$P" \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['access_token'])"
