#!/usr/bin/env bash
# Sync the deployment SOURCE (clean_src) into the RUNTIME — the same code sync
# airgap_build_step3 does, but safe to run standalone.
#
#   util/sync-runtime.sh [-n] [SRC] [DEST]
#     -n | --dry-run   preview only (rsync --dry-run), change nothing
#     SRC   default: ${INSTALL_SRC_DIR:-/mnt/install_src}/clean_src/digitaltwins-platform
#     DEST  default: $HOME/digitaltwins-platform
#
# Mirrors code with --delete, but PROTECTS the runtime-generated / git-ignored
# state that clean_src (a git checkout) does NOT contain — so it never wipes your
# generated .env, TLS certs, imported realm, SEEK env, DAGs, or logs. After it
# runs, recreate changed services with `docker compose up -d`.
set -euo pipefail

DRY=""
case "${1:-}" in
  -n|--dry-run) DRY="--dry-run"; shift ;;
esac

SRC="${1:-${INSTALL_SRC_DIR:-/mnt/install_src}/clean_src/digitaltwins-platform}"
DEST="${2:-$HOME/digitaltwins-platform}"

[ -d "$SRC" ]  || { echo "sync-runtime: source not found: $SRC"  >&2; exit 1; }
[ -d "$DEST" ] || { echo "sync-runtime: dest not found:   $DEST" >&2; exit 1; }

# git-ignored / runtime-generated state clean_src does NOT hold — never delete:
excludes=(
  --exclude='.git/'
  --exclude='.env'                                             # generated by gen-env.sh
  --exclude='services/airflow/dags/'                           # managed via sync-dags.sh
  --exclude='services/airflow/logs/'                           # runtime logs
  --exclude='services/keycloak/import/'                        # rendered realm (gen-realm.sh)
  --exclude='services/nginx/certs/'                            # installed TLS certs
  --exclude='services/seek/ldh-deployment/docker-compose.env'  # rendered SEEK env
)

echo "sync-runtime: ${DRY:+[dry-run] }$SRC/  ->  $DEST/"
# shellcheck disable=SC2086  # $DRY is intentionally word-split (empty = no flag)
rsync -a --delete ${DRY} "${excludes[@]}" "$SRC/" "$DEST/"
echo "sync-runtime: done.${DRY:+ (dry-run — nothing changed)}"
