#!/usr/bin/env bash
# Sync the deployment SOURCE (clean_src) into the RUNTIME — the same code sync
# airgap_build_step3 does, but safe to run standalone.
#
#   util/sync-runtime.sh [-n] [SRC] [DEST]
#     -n | --dry-run   preview only (rsync --dry-run), change nothing
#     SRC   default: ${INSTALL_SRC_DIR:-/mnt/install_src}/clean_src/digitaltwins-platform
#     DEST  default: $HOME/digitaltwins-platform
#     DATA_DIR (env) default: ${INSTALL_SRC_DIR:-/mnt/install_src}/data
#
# 1. Mirrors code with --delete, but PROTECTS the runtime-generated / git-ignored
#    state that clean_src (a git checkout) does NOT contain — so it never wipes
#    your generated .env, TLS certs, imported realm, SEEK env, DAGs, or logs.
# 2. Then RENDERS any of those generated files that are MISSING (from DATA_DIR),
#    so a fresh runtime comes out complete and a stray earlier --delete can't
#    leave the portal dead. Existing files are left untouched.
#
# After it runs, recreate changed services with `docker compose up -d`.
set -euo pipefail

DRY=""
case "${1:-}" in
  -n|--dry-run) DRY="--dry-run"; shift ;;
esac

SRC="${1:-${INSTALL_SRC_DIR:-/mnt/install_src}/clean_src/digitaltwins-platform}"
DEST="${2:-$HOME/digitaltwins-platform}"
DATA_DIR="${DATA_DIR:-${INSTALL_SRC_DIR:-/mnt/install_src}/data}"

[ -d "$SRC" ]  || { echo "sync-runtime: source not found: $SRC"  >&2; exit 1; }
[ -d "$DEST" ] || { echo "sync-runtime: dest not found:   $DEST" >&2; exit 1; }

# git-ignored / runtime-generated state clean_src does NOT hold — never delete:
excludes=(
  --exclude='.git/'
  --exclude='.env'                                             # generated by gen-env.sh
  --exclude='services/airflow/dags/'                           # managed via sync-dags.sh
  --exclude='services/airflow/logs/'                           # runtime logs
  --exclude='services/keycloak/import/'                        # rendered realm (gen-realm.sh)
  --exclude='services/nginx/certs/'                            # installed TLS certs
  --exclude='services/seek/ldh-deployment/docker-compose.env'  # rendered SEEK env
)

echo "sync-runtime: ${DRY:+[dry-run] }$SRC/  ->  $DEST/"
# In a dry-run, itemize so the operator actually SEES what would change — without
# it, rsync is silent and the run looks like a no-op even when it isn't.
# shellcheck disable=SC2086  # $DRY / itemize flag are intentionally word-split (empty = no flag)
rsync -a --delete ${DRY} ${DRY:+--itemize-changes} "${excludes[@]}" "$SRC/" "$DEST/"

# --- render generated files that are MISSING (never overwrite existing) -------
render_missing() {
  local env="$DATA_DIR/env" secrets="$DATA_DIR/secrets.env"
  if [ ! -d "$DATA_DIR" ]; then
    echo "sync-runtime: DATA_DIR '$DATA_DIR' not found — skipping generated-file render"
    return 0
  fi
  cd "$DEST"

  # SEEK's MySQL env (from secrets.env). Passwords must match the seek_db volume.
  local seekenv=services/seek/ldh-deployment/docker-compose.env
  if [ ! -f "$seekenv" ] && [ -f "$secrets" ]; then
    echo "  render (missing): $seekenv"
    ( set -a; . "$secrets"; set +a
      cat > "$seekenv" <<EOF
MYSQL_HOST=db
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD not set in $secrets}
MYSQL_DATABASE=seek
MYSQL_USER=seek
MYSQL_PASSWORD=${MYSQL_PASSWORD:?MYSQL_PASSWORD not set in $secrets}
EOF
    )
    chmod 600 "$seekenv"
  fi

  # Keycloak realm import (rendered from its template).
  local realm=services/keycloak/import/digitaltwins-realm.json
  if [ ! -f "$realm" ] && [ -f "$env" ] && [ -f "$secrets" ]; then
    echo "  render (missing): $realm"
    ./util/gen-realm.sh -e "$env" -s "$secrets"
  fi

  # Gateway TLS certs — https deploys have data/fullchain.pem (a symlink; install derefs it).
  if [ ! -f services/nginx/certs/server.crt ] && [ -e "$DATA_DIR/fullchain.pem" ]; then
    echo "  render (missing): gateway TLS certs"
    mkdir -p services/nginx/certs
    install -m 0644 "$DATA_DIR/fullchain.pem" services/nginx/certs/server.crt
    install -m 0600 "$DATA_DIR/privkey.pem"   services/nginx/certs/server.key
  fi
}

if [ -z "$DRY" ]; then
  render_missing
fi

if [ -n "$DRY" ]; then
  echo "sync-runtime: dry-run complete — the itemized lines above are what a real"
  echo "              run WOULD write (nothing was changed). Empty list = in sync."
else
  echo "sync-runtime: done."
fi
