services:
  minio:
    image: quay.io/minio/minio:latest
    ports:
      - '8011:9000' #api
      - '8012:9001' # web gui
    networks:
      - digitaltwins
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_SERVER_ACCESS_KEY=${MINIO_SERVER_ACCESS_KEY:-minioadmin}
      - MINIO_SERVER_SECRET_KEY=${MINIO_SERVER_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001" --address ":9000"

volumes:
  minio_data:
    driver: local

networks:
  digitaltwins:
    driver: bridge
