# create https-key-store-file, Run:
# keytool -genkeypair \
#  -alias keycloak \
#  -keyalg RSA \
#  -keystore server.jks \
#  -storepass change_me \
#  -keypass change_me \
#  -validity 365 \
#  -dname "CN=localhost, OU=Dev, O=MyCompany, L=City, ST=State, C=NZ"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    command:
      - start
      - --hostname-strict=false
      - --http-enabled=true
      - --https-key-store-file=/opt/keycloak/conf/server.jks
      - --https-key-store-password=${KC_HTTPS_KEY_STORE_PASSWORD}
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
    ports:
      - "8009:8443"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./server.jks:/opt/keycloak/conf/server.jks
    restart: unless-stopped
    networks:
      - digitaltwins

volumes:
  keycloak_data:
    driver: local

networks:
  digitaltwins:
    driver: bridge

# Keycloak Admin Console
# http://localhost:8080/admin

# keycloak account console
# http://localhost:8080/realms/<myrealm>/account
# http://localhost:8080/realms/digitaltwins/account


# creating network
# sudo docker network create digitaltwins
