# Generate a self-signed X.509 cert (run once before first deploy):
# openssl req -x509 -newkey rsa:2048 -days 3650 -nodes \
#   -keyout services/keycloak/key/tls.key \
#   -out    services/keycloak/key/tls.crt \
#   -subj "/CN=localhost/OU=Dev/O=DigitalTWINS/L=Auckland/ST=Auckland/C=NZ"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    command:
      - start
      - --hostname-strict=false
      - --http-enabled=true
      - --https-certificate-file=/opt/keycloak/conf/tls.crt
      - --https-certificate-key-file=/opt/keycloak/conf/tls.key
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
    ports:
      - "8009:8443"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./key/tls.crt:/opt/keycloak/conf/tls.crt:ro
      - ./key/tls.key:/opt/keycloak/conf/tls.key:ro
      - ./digitaltwins-login-theme:/opt/keycloak/themes/digitaltwins-login-theme:ro

    restart: unless-stopped
    networks:
      - digitaltwins

volumes:
  keycloak_data:
    driver: local

networks:
  digitaltwins:
    driver: bridge

# Keycloak Admin Console
# http://localhost:8080/admin

# keycloak account console
# http://localhost:8080/realms/<myrealm>/account
# http://localhost:8080/realms/digitaltwins/account


# creating network
# sudo docker network create digitaltwins
