import os
from pathlib import Path
from typing import Dict, Any, Optional
from .logger import get_logger
import subprocess
import shlex
from app.client.minio import get_minio_client
from sqlalchemy.orm import Session
from app.models.db_model import Plugin, SessionLocal

logger = get_logger(__name__)

# Directory where portal-backend writes plugin nginx configs (shared volume with portal-frontend)
NGINX_PLUGINS_CONF_DIR = os.environ.get(
    "NGINX_PLUGINS_CONF_DIR", "/nginx-plugins-conf"
)
# Container name of the portal-frontend (nginx) service for docker exec
NGINX_CONTAINER_NAME = os.environ.get("NGINX_CONTAINER_NAME", "portal-frontend")


class PluginDeployer:
    """Handle Deploy plugin backend"""

    def __init__(self):
        pass

    # ── Nginx config helpers ────────────────────────────────────────

    @staticmethod
    def generate_nginx_conf(
        expose_name: str,
        internal_host: str,
        internal_port: str,
        has_websocket: bool = True,
    ) -> str:
        """Generate and write an nginx location config file for a plugin."""
        route_prefix = f"/plugin/{expose_name}"

        conf = f"""# Auto-generated by portal-backend at deploy time
# Plugin: {expose_name}

location {route_prefix}/ {{
    proxy_pass http://{internal_host}:{internal_port}/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 86400;
}}
"""
        conf_path = Path(NGINX_PLUGINS_CONF_DIR) / f"{expose_name}.conf"
        conf_path.parent.mkdir(parents=True, exist_ok=True)
        conf_path.write_text(conf, encoding="utf-8")
        logger.info(f"Generated nginx config: {conf_path}")
        return str(conf_path)

    @staticmethod
    def remove_nginx_conf(expose_name: str) -> bool:
        """Remove the nginx config file for a plugin."""
        conf_path = Path(NGINX_PLUGINS_CONF_DIR) / f"{expose_name}.conf"
        if conf_path.exists():
            conf_path.unlink()
            logger.info(f"Removed nginx config: {conf_path}")
            return True
        logger.warning(f"Nginx config not found for removal: {conf_path}")
        return False

    @staticmethod
    def reload_nginx() -> bool:
        """Reload nginx to pick up config changes."""
        try:
            result = subprocess.run(
                ["docker", "exec", NGINX_CONTAINER_NAME, "nginx", "-s", "reload"],
                capture_output=True, text=True, timeout=10,
            )
            if result.returncode == 0:
                logger.info("Nginx reloaded successfully")
                return True
            else:
                logger.error(f"Nginx reload failed: {result.stderr}")
                return False
        except Exception as e:
            logger.error(f"Failed to reload nginx: {e}")
            return False

    @staticmethod
    def _check_compose_file(backend_dir: Path):
        compose_yml = backend_dir / 'docker-compose.yml'
        compose_yaml = backend_dir / 'docker-compose.yaml'
        if compose_yml.exists() or compose_yaml.exists():
            logger.info("Docker compose file is exist")
            return True
        else:
            logger.error("Docker compose file is not exist")
            raise Exception("Docker compose file is not exist")

    @staticmethod
    def _compose_execute(backend_dir: Path, command: str, extra_env: dict = None):
        try:
            logger.info(f"Running command {command} for deployment of {backend_dir}")
            # Merge current process env with any extra vars (e.g. PLUGIN_ROUTE_PREFIX).
            # docker compose picks up env vars from the process environment to substitute
            # ${VAR} references in docker-compose.yml.
            env = os.environ.copy()
            if extra_env:
                env.update(extra_env)
            with subprocess.Popen(
                    shlex.split(command),
                    cwd=backend_dir,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    bufsize=1,
                    env=env,
            ) as process:
                for line in process.stdout:
                    logger.info(line.strip())

                return_code = process.wait()
                if return_code == 0:
                    logger.info("Docker compose command executed successfully.")
                else:
                    logger.error(f"Docker compose command failed with return code: {return_code}")

        except FileNotFoundError as e:
            logger.error(f"Docker or Docker Compose has not been installed or configured correctly. Error: {e}")
        except Exception as e:
            logger.error(f"An unexpected error occurred when running docker compose up: {e}")

    @staticmethod
    def _build_compose_command(
        expose_name: str,
        action: str = "up --build -d --force-recreate",
    ) -> str:
        """Build a docker compose command with project name scoped to the plugin."""
        return f"docker compose -p {expose_name} {action}"

    def deploy(self, plugin: Dict[str, Any]) -> Dict[str, Any]:

        deploy_logs = []
        expose_name = plugin.get("expose_name", )
        dataset_path = plugin.get("dataset_path", "unknown")
        backend_folder = plugin.get("backend_folder", "unknown")

        try:
            # Step 1 get backend dir
            backend_dir = Path(dataset_path) / "code" / backend_folder
            logger.info(f"Step 1: Get backend dir {backend_dir.as_posix()} for docker deploy...")
            # Step 2: check if docker-compose.yml exist
            logger.info("Step 2: Check docker compose file...")
            self._check_compose_file(backend_dir)
            # Step 3 deploy backend in docker with project name = expose_name
            logger.info(f"Step 3: Start docker compose with project name '{expose_name}'...")
            deploy_command = self._build_compose_command(expose_name, "up --build -d --force-recreate")
            self._compose_execute(backend_dir, deploy_command, extra_env={"PLUGIN_ROUTE_PREFIX": f"/plugin/{expose_name}"})
            return {
                "success": True,
                "backend_dir": str(backend_dir) if backend_dir else None,
                "deploy_logs": "\n".join(deploy_logs)
            }

        except Exception as e:
            error_message = str(e)
            logger.info(f"Deploy failed: {error_message}")
            logger.error(f"Deploy process failed: {e}")

            return {
                "success": False,
                "backend_dir": None,
                "deploy_logs": "\n".join(deploy_logs),
                "error_message": error_message
            }

    def compose_up(self, plugin: Dict[str, Any]) -> Dict[str, Any]:
        dir_path = plugin.get("backend_dir", "unknown")
        expose_name = plugin.get("expose_name", "")
        if dir_path is None or dir_path == "unknown":
            return {"success": False, "backend_dir": None}

        backend_dir = Path(dir_path)
        command = self._build_compose_command(expose_name, "up -d") if expose_name else "docker compose up -d"

        if backend_dir.exists():
            try:
                extra_env = {"PLUGIN_ROUTE_PREFIX": f"/plugin/{expose_name}"} if expose_name else None
                self._compose_execute(backend_dir, command, extra_env=extra_env)
                logger.info(f"successfully run compose up for project '{expose_name}' at {backend_dir}")
                return {
                    "success": True,
                    "message": f"successfully run compose up for project '{expose_name}' at {backend_dir}",
                }
            except Exception as e:
                logger.error(f"Failed compose up for project '{expose_name}' at {backend_dir}, error: {e}")
                return {
                    "success": False,
                    "message": f"Failed compose up for project '{expose_name}' at {backend_dir}, error: {e}",
                }
        else:
            logger.error(f"Docker compose up failed, backend_dir {backend_dir} does not exist")
            return {
                "success": False,
                "message": f"Docker compose up for {backend_dir} does not exist",
            }

    def compose_down(self, plugin: Dict[str, Any]) -> Dict[str, Any]:
        dir_path = plugin.get("backend_dir", "unknown")
        expose_name = plugin.get("expose_name", "")
        if dir_path is None or dir_path == "unknown":
            return {"success": False, "backend_dir": None}

        backend_dir = Path(dir_path)
        command = self._build_compose_command(expose_name, "down") if expose_name else "docker compose down"

        if backend_dir.exists():
            try:
                self._compose_execute(backend_dir, command)
                logger.info(f"successfully run compose down for project '{expose_name}' at {backend_dir}")
                return {
                    "success": True,
                    "message": f"successfully run compose down for project '{expose_name}' at {backend_dir}",
                }
            except Exception as e:
                logger.error(f"Failed compose down for project '{expose_name}' at {backend_dir}, error: {e}")
                return {
                    "success": False,
                    "message": f"Failed compose down for project '{expose_name}' at {backend_dir}, error: {e}",
                }
        else:
            logger.error(f"Docker compose down failed, backend_dir {backend_dir} does not exist")
            return {
                "success": False,
                "message": f"Docker compose down for {backend_dir} does not exist",
            }

    def delete(self, plugin: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute docker compose down and,
        Remove all images and volumes which belong to this compose
        """
        dir_path = plugin.get("backend_dir", "unknown")
        expose_name = plugin.get("expose_name", "")
        if dir_path is None or dir_path == "unknown":
            return {"success": False, "backend_dir": None}

        backend_dir = Path(dir_path)
        command = self._build_compose_command(expose_name, "down --rmi all --volumes") if expose_name else "docker compose down --rmi all --volumes"

        if backend_dir.exists():
            try:
                self._compose_execute(backend_dir, command)
                # Also remove the nginx config for this plugin
                self.remove_nginx_conf(expose_name)
                self.reload_nginx()
                # Remove any remaining Docker volumes whose names start with expose_name
                if expose_name:
                    self._remove_volumes_by_prefix(expose_name)
                logger.info(f"successfully removed all images and volumes for project '{expose_name}' at {backend_dir}")
                return {
                    "success": True,
                    "message": f"successfully removed all images and volumes for project '{expose_name}' at {backend_dir}",
                }
            except Exception as e:
                logger.error(f"Failed removed all images and volumes for project '{expose_name}' at {backend_dir}, error: {e}")
                return {
                    "success": False,
                    "message": f"Failed removed all images and volumes for project '{expose_name}' at {backend_dir}, error: {e}",
                }
        else:
            logger.error(f"Removed all images and volumes failed, backend_dir {backend_dir} does not exist")
            return {
                "success": False,
                "message": f"Removed all images and volumes failed, because {backend_dir} does not exist",
            }

    def _remove_volumes_by_prefix(self, expose_name: str) -> None:
        """Find and remove all Docker volumes whose names start with expose_name."""
        try:
            result = subprocess.run(
                ["docker", "volume", "ls", "--filter", f"name={expose_name}", "--quiet"],
                capture_output=True,
                text=True,
            )
            volumes = [v.strip() for v in result.stdout.splitlines() if v.strip().startswith(expose_name)]
            if not volumes:
                logger.info(f"No extra volumes found with prefix '{expose_name}'")
                return
            subprocess.run(["docker", "volume", "rm"] + volumes, capture_output=True, text=True)
            logger.info(f"Removed volumes with prefix '{expose_name}': {volumes}")
        except Exception as e:
            logger.warning(f"Failed to remove volumes with prefix '{expose_name}': {e}")
